FROM node:20-alpine
WORKDIR /app

RUN apk add python3 make g++ && \
    corepack enable && \
    corepack prepare pnpm@8.7.1 --activate

COPY ./ /app/
RUN npm config set -L project @mtcute:registry http://verdaccio:4873/ && \
    chmod +x ./docker-entrypoint.sh

ENTRYPOINT [ "./docker-entrypoint.sh" ]
CMD [ "all" ]