FROM denoland/deno:bin-1.43.1 as deno-bin

FROM node:20
WORKDIR /app

COPY --from=deno-bin /deno /bin/deno

RUN corepack enable && \
    corepack prepare pnpm@8.7.1 --activate

COPY ../.. /app/

RUN pnpm install --frozen-lockfile && \
    pnpm -C packages/tl run gen-code

RUN apt update && apt install -y socat

ENV REGISTRY="http://jsr/"
ENV E2E="1"
ENV JSR="1"
ENV JSR_TOKEN="token"

ENTRYPOINT [ "node", "/app/scripts/publish.js" ]
CMD [ "all" ]