/* eslint-disable @typescript-eslint/no-unused-vars */
// @copy
import {
    BaseTelegramClient,
    BaseTelegramClientOptions,
    ITelegramStorage,
    Long,
    MaybeArray,
    MaybeAsync,
    PartialExcept,
    PartialOnly,
    tl,
} from '@mtcute/core'
// @copy
import { tdFileId } from '@mtcute/file-id'

// @copy
import {
    AllStories,
    ArrayPaginated,
    ArrayWithTotal,
    Booster,
    BoostStats,
    BotChatJoinRequestUpdate,
    BotCommands,
    BotStoppedUpdate,
    CallbackQuery,
    Chat,
    ChatEvent,
    ChatInviteLink,
    ChatInviteLinkMember,
    ChatJoinRequestUpdate,
    ChatMember,
    ChatMemberUpdate,
    ChatPreview,
    ChosenInlineResult,
    DeleteMessageUpdate,
    DeleteStoryUpdate,
    Dialog,
    FileDownloadLocation,
    FileDownloadParameters,
    ForumTopic,
    GameHighScore,
    HistoryReadUpdate,
    InlineCallbackQuery,
    InlineQuery,
    InputChatEventFilters,
    InputDialogFolder,
    InputFileLike,
    InputInlineResult,
    InputMediaLike,
    InputMessageId,
    InputPeerLike,
    InputPrivacyRule,
    InputReaction,
    InputStickerSet,
    InputStickerSetItem,
    InputText,
    MaybeDynamic,
    Message,
    MessageMedia,
    MessageReactions,
    ParametersSkip2,
    ParsedUpdate,
    PeerReaction,
    PeersIndex,
    PeerStories,
    Photo,
    Poll,
    PollUpdate,
    PollVoteUpdate,
    PreCheckoutQuery,
    RawDocument,
    ReplyMarkup,
    SentCode,
    Sticker,
    StickerSet,
    StickerSourceType,
    StickerType,
    StoriesStealthMode,
    Story,
    StoryInteractions,
    StoryUpdate,
    StoryViewer,
    StoryViewersList,
    TakeoutSession,
    TextWithEntities,
    TypingStatus,
    UploadedFile,
    UploadFileLike,
    User,
    UserStatusUpdate,
    UserTypingUpdate,
} from '../types/index.js'
