import type { tl } from '../../../tl/index.js'
import type { ITelegramClient } from '../../client.types.js'
import type { InputMessageId, InputPollAnswer, InputText } from '../../types/index.js'
import { normalizeInputMessageId } from '../../types/index.js'
import { _normalizeInputPollAnswer } from '../files/normalize-input-media.js'
import { resolvePeer } from '../users/resolve-peer.js'

/**
 * Suggest a new answer to a poll.
 *
 * Only possible in polls with {@link Poll.canAddAnswers} set
 */
export async function addPollAnswer(
  client: ITelegramClient,
  params: InputMessageId & {
    /** The answer to add */
    answer: InputText | InputPollAnswer | tl.TypePollAnswer

    /**
     * Whether to dispatch the updates that will be generated by this call
     * to the client's update handler.
     */
    shouldDispatch?: true

    /**
     * Upload progress callback for the answer media
     *
     * @param uploaded  Number of bytes uploaded
     * @param total  Total file size
     */
    progressCallback?: (uploaded: number, total: number) => void
  },
): Promise<void> {
  const { chatId, message } = normalizeInputMessageId(params)
  const peer = await resolvePeer(client, chatId)

  const res = await client.call({
    _: 'messages.addPollAnswer',
    peer,
    msgId: message,
    answer: await _normalizeInputPollAnswer(client, params.answer, {
      progressCallback: params.progressCallback,
      uploadPeer: peer,
    }),
  })

  client.handleClientUpdate(res, !params.shouldDispatch)
}
