import type { ITelegramClient } from '../../client.types.js'
import type { InputMessageId } from '../../types/index.js'
import { normalizeInputMessageId } from '../../types/index.js'
import { resolvePeer } from '../users/resolve-peer.js'

/**
 * Delete an answer that was suggested to a poll
 */
export async function deletePollAnswer(
  client: ITelegramClient,
  params: InputMessageId & {
    /** Data of the answer to delete (see {@link PollAnswer.data}) */
    option: Uint8Array

    /**
     * Whether to dispatch the updates that will be generated by this call
     * to the client's update handler.
     */
    shouldDispatch?: true
  },
): Promise<void> {
  const { chatId, message } = normalizeInputMessageId(params)

  const res = await client.call({
    _: 'messages.deletePollAnswer',
    peer: await resolvePeer(client, chatId),
    msgId: message,
    option: params.option,
  })

  client.handleClientUpdate(res, !params.shouldDispatch)
}
