import type { ITelegramClient } from '../../client.types.js'
import type { InputMessageId, InputPeerLike } from '../../types/index.js'
import { assertTrue } from '../../../utils/type-assertions.js'
import { normalizeInputMessageId } from '../../types/index.js'
import { resolvePeer } from '../users/resolve-peer.js'

/**
 * Delete all reactions added by the given sender on a message.
 *
 * Requires the `deleteMessages` admin right.
 */
export async function deleteMessageReactionsFromSender(
  client: ITelegramClient,
  params: InputMessageId & {
    /** Sender whose reactions should be deleted */
    sender: InputPeerLike

    /**
     * Whether to dispatch updates that will be generated by this call.
     * Doesn't follow `disableNoDispatch`
     */
    shouldDispatch?: true
  },
): Promise<void> {
  const { chatId, message } = normalizeInputMessageId(params)

  const res = await client.call({
    _: 'messages.deleteParticipantReaction',
    peer: await resolvePeer(client, chatId),
    msgId: message,
    participant: await resolvePeer(client, params.sender),
  })

  client.handleClientUpdate(res, !params.shouldDispatch)
}

/**
 * Delete all recent reactions added by the given sender in a chat.
 *
 * Only supported for groups and supergroups, requires the `deleteMessages` admin right.
 *
 * @param chatId  Chat ID
 * @param senderId  Sender whose reactions should be deleted
 */
export async function deleteRecentReactionsFromSender(
  client: ITelegramClient,
  chatId: InputPeerLike,
  senderId: InputPeerLike,
): Promise<void> {
  const res = await client.call({
    _: 'messages.deleteParticipantReactions',
    peer: await resolvePeer(client, chatId),
    participant: await resolvePeer(client, senderId),
  })

  assertTrue('messages.deleteParticipantReactions', res)
}
