import type { ITelegramClient } from '../../client.types.js'
import type { InputPeerLike } from '../../types/index.js'
import { createDummyUpdate } from '../../updates/utils.js'
import { isInputPeerChannel } from '../../utils/peer-utils.js'
import { resolvePeer } from '../users/resolve-peer.js'

/**
 * Mark all reactions in chat as read.
 *
 * @param chatId  Chat ID
 */
export async function readReactions(
  client: ITelegramClient,
  chatId: InputPeerLike,
  params?: {
    /**
     * For forums - read reactions only in the given topic
     */
    topicId?: number

    /**
     * For saved messages and monoforums (channel direct messages),
     * peer identifying the topic to read reactions in
     */
    topicPeer?: InputPeerLike

    /**
     * Whether to dispatch updates that will be generated by this call.
     * Doesn't follow `disableNoDispatch`
     */
    shouldDispatch?: true
  },
): Promise<void> {
  const { topicId, topicPeer, shouldDispatch } = params ?? {}
  const peer = await resolvePeer(client, chatId)
  const res = await client.call({
    _: 'messages.readReactions',
    peer,
    topMsgId: topicId,
    savedPeerId: topicPeer ? await resolvePeer(client, topicPeer) : undefined,
  })

  if (!shouldDispatch) {
    if (isInputPeerChannel(peer)) {
      client.handleClientUpdate(createDummyUpdate(res.pts, res.ptsCount, peer.channelId))
    } else {
      client.handleClientUpdate(createDummyUpdate(res.pts, res.ptsCount))
    }
  }
}
