import type { ITelegramClient } from '../../client.types.js'
import type { InputPeerLike } from '../../types/index.js'
import { createDummyUpdate } from '../../updates/utils.js'
import { isInputPeerChannel } from '../../utils/peer-utils.js'
import { resolvePeer } from '../users/resolve-peer.js'

/**
 * Mark all unread poll votes in chat as read.
 *
 * @param chatId  Chat ID
 */
export async function readPollVotes(
  client: ITelegramClient,
  chatId: InputPeerLike,
  params?: {
    /** If passed, only votes in polls in this thread (topic) will be marked as read */
    threadId?: number

    /**
     * Whether to dispatch updates that will be generated by this call.
     * Doesn't follow `disableNoDispatch`
     */
    shouldDispatch?: true
  },
): Promise<void> {
  const { threadId, shouldDispatch } = params ?? {}
  const peer = await resolvePeer(client, chatId)

  for (;;) {
    const res = await client.call({
      _: 'messages.readPollVotes',
      peer,
      topMsgId: threadId,
    })

    if (!shouldDispatch) {
      client.handleClientUpdate(
        createDummyUpdate(res.pts, res.ptsCount, isInputPeerChannel(peer) ? peer.channelId : 0),
      )
    }

    if (!res.offset) break
  }
}
