/* eslint-disable unused-imports/no-unused-imports */

// @copy
import { tdFileId } from '@mtcute/file-id'
// @copy
import { RpcCallOptions } from '../../network/index.js'

// @copy
import { tl } from '../../tl/index.js'
// @copy
import { MaybeArray, MaybePromise, MtUnsupportedError, PartialExcept, PartialOnly } from '../../types/index.js'
// @copy
import { BaseTelegramClient, BaseTelegramClientOptions } from '../base.js'
// @copy
import { ITelegramClient } from '../client.types.js'
// @copy
import {
  AllStories,
  ArrayPaginated,
  ArrayPaginatedWithMeta,
  ArrayWithTotal,
  Audio,
  Boost,
  BoostSlot,
  BoostStats,
  BotAccessSettings,
  BotChatJoinRequestUpdate,
  BotCommands,
  BotGuestChatQuery,
  BotReactionCountUpdate,
  BotReactionUpdate,
  BotStoppedUpdate,
  BotSubscriptionUpdate,
  BusinessCallbackQuery,
  BusinessChatLink,
  BusinessConnection,
  BusinessMessage,
  BusinessWorkHoursDay,
  CallbackQuery,
  Chat,
  ChatEvent,
  ChatInviteLink,
  ChatInviteLinkMember,
  ChatJoinRequestUpdate,
  ChatJoinResultUpdate,
  ChatlistPreview,
  ChatMember,
  ChatMemberUpdate,
  ChatPreview,
  ChosenInlineResult,
  CollectibleInfo,
  CommunityPeerRequest,
  DeleteBusinessMessageUpdate,
  DeleteEphemeralMessagesUpdate,
  DeleteMessageUpdate,
  DeleteStoryUpdate,
  Dialog,
  EphemeralCallbackQuery,
  EphemeralMessage,
  FactCheck,
  FileDownloadLocation,
  FileDownloadParameters,
  ForumTopic,
  FullChat,
  FullUser,
  GameHighScore,
  HistoryReadUpdate,
  InlineCallbackQuery,
  InlineQuery,
  InputChatEventFilters,
  InputDialogFolder,
  InputDocumentId,
  InputFileLike,
  InputInlineMessage,
  InputInlineResult,
  InputMediaAudio,
  InputMediaLike,
  InputMediaSticker,
  InputMessageId,
  InputPeerLike,
  InputPollAnswer,
  InputPrivacyRule,
  InputReaction,
  InputReplyKeyboardButton,
  InputRichMessage,
  InputStarGift,
  InputStickerSet,
  InputStickerSetItem,
  InputText,
  InputWebview,
  ManagedBotUpdate,
  MaybeDynamic,
  Message,
  MessageEffect,
  MessageMedia,
  MessageReactions,
  ParametersSkip2,
  ParsedUpdate,
  Peer,
  PeerReaction,
  PeerSettings,
  PeersIndex,
  PeerStories,
  Photo,
  Poll,
  PollUpdate,
  PollVoteUpdate,
  PreCheckoutQuery,
  RawDocument,
  ReplyMarkup,
  RichMediaUploadCache,
  SavedStarGift,
  SendableTypingStatus,
  SentCode,
  StarGift,
  StarGiftUnique,
  StarGiftValue,
  StarsStatus,
  StarsTransaction,
  StatsGraph,
  Sticker,
  StickerSet,
  StickerSourceType,
  StickerType,
  StoriesStealthMode,
  Story,
  StoryInteractions,
  StoryUpdate,
  StoryViewer,
  StoryViewersList,
  TakeoutSession,
  TextWithEntities,
  TypingStatus,
  UploadedFile,
  UploadFileLike,
  User,
  UserStatusUpdate,
  UserTypingUpdate,
  WebPageMedia,
  WebviewPlatform,
  WebviewResult,
  WebviewThemeParams,
} from '../types/index.js'
// @copy
import { RawUpdateInfo } from '../updates/types.js'
// @copy
import { InputStringSessionData } from '../utils/string-session.js'
